---

- name: prepare main config
  template:
    src: main_cfg.j2
    dest: "{{ consul_config_dir }}/{{ consul_cfg_name }}"
    owner: root
    group: "{{ consul_group }}"
    mode: 0640
  notify: restart consul service

- name: generate services config
  template:
    src: consul_service.j2
    dest: "{{ consul_config_dir }}/service-{{ item | json_query(\"service.id\") }}.json"
    owner: root
    group: "{{ consul_group }}"
    mode: 0640
  loop: "{{ consul_services }}"
  notify: restart consul service
  when: consul_services | length > 0

- name: prepare systemd unit
  template:
    src: systemd_unit.j2
    dest: "/etc/systemd/system/{{ consul_service_name }}.service"
    owner: root
    group: root
  notify:
    - reload consul unit
    - restart consul service

- name: enable service
  service:
    name: "{{ consul_service_name }}"
    state: started
    enabled: true
