---

- name: create group
  group:
    name: "{{ consul_group }}"
    system: true
    state: present

- name: create user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    shell: "/bin/false"
    home: "/etc/consul.d"
    create_home: false
    system: true
    comment: "Consul user"
    state: present

- name: create conf dir if necesary
  file:
    path: "{{ consul_config_dir }}"
    state: directory
    owner: root
    group: "{{ consul_group }}"
    mode: 0750

- name: create data dir if necesary
  file:
    path: "{{ consul_data_dir }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0750
